project_id = "hjecjqyonxvrrvprbvgr"

[functions.verify-payment]
verify_jwt = true

[functions.add-device-slot]
verify_jwt = true

[functions.sync-device-slots]
verify_jwt = true

[functions.log-activity]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.add-to-audience]
verify_jwt = false

[functions.sync-users-to-audience]
verify_jwt = true

[functions.cleanup-activity-logs]
verify_jwt = false

[functions.send-trial-reminder]
verify_jwt = false

[functions.send-renewal-invoices]
verify_jwt = false
